/*
    MotorControlTask.cpp

    This file implements the fast hardware-facing control loop.

    Main responsibilities:
      1. call Hardware.cpp to update the real motor control step
      2. read angle / velocity / currents from the hardware layer
      3. write the latest measured state into SharedState
      4. read the latest command generated by the model task
      5. apply that command to the motor

    This task should NOT contain the resistor/capacitor/inductor/diode math.
    Its job is to execute commands, not invent them.

    Think of this task as:
      "measure the real system and drive the real motor"
*/
