/*
    SharedState.cpp

    This file owns the actual shared-memory objects used by the system
    and provides the synchronization layer used to access them safely.

    In our firmware, multiple tasks may need access to the same data:
      - the control task may publish the latest measured motor state
      - telemetry may read that measured state to print/debug it
      - telemetry or setup code may update the runtime config
      - the control task may publish the latest haptic command
      - watchdog / supervisory code may update or inspect system flags

    Since these tasks can run at different times and potentially interrupt
    one another, we need a safe way to protect shared data from concurrent
    access. That is the purpose of the mutex in this file.

    So, in practice, this file provides:
      - the actual global shared-state objects
      - the mutex that protects them
      - helper functions for safe reads and writes

    This file only provides the shared memory layer that lets tasks communicate safely.
*/

#include "SharedState.h"

// ======== GLOBAL SHARED-STATE OBJECTS ======
//
// These are the actual storage locations that all tasks in the system
// may need to read from or write to.
//
// g_system_state:
//   Holds high-level system flags and status information, such as whether
//   control is enabled, whether a fault is latched, heartbeat timestamps, etc.
//
// g_measured_state:
//   Holds the latest measured motor/knob state produced by the control task.
//   This includes things like angle, velocity, acceleration, currents, etc.
//
// g_haptic_command:
//   Holds the most recent output command generated by the haptic model layer.
//
// g_runtime_config:
//   Holds the currently selected runtime settings / model parameters.
//
// g_state_mutex:
//   A FreeRTOS mutex used to make sure only one task at a time is accessing
//   or modifying the shared-state objects above.
SystemState g_system_state;
MeasuredState g_measured_state;
HapticCommand g_haptic_command;
RuntimeConfig g_runtime_config;
SemaphoreHandle_t g_state_mutex = nullptr;

// ================ SHARED-STATE INITIALIZATION ==============
// This function must be called once during startup before any tasks try
// to use the shared-state read/write helpers.
//
// What it does:
//   - creates the mutex that protects the shared-state objects
//
// If the mutex is not created successfully, shared-state access is not safe,
// so the function returns false.
//
bool initSharedState()
{
    // Create a FreeRTOS mutex.
    //
    // A mutex is used here because we want mutually exclusive access:
    // only one task at a time should read/write the shared objects while
    // the lock is held.
    g_state_mutex = xSemaphoreCreateMutex();

    // Return true only if creation succeeded.
    return (g_state_mutex != nullptr);
}

// ==================  MEASURED STATE READ / WRITE ============
//
// The measured state is typically written by the control task and read by telemetry
//
// General pattern used by all read/write helpers in this file:
//
//   1. make sure the mutex exists
//   2. take the mutex
//   3. copy the shared object
//   4. release the mutex
//   5. return success
//
// We copy whole structs in one shot so callers get a clean snapshot
// of the data.

// Read the latest measured state into the caller-provided output variable.
bool readMeasuredState(MeasuredState &out)
{
    // If the mutex does not exist yet, shared-state access has not been
    // initialized properly, so fail safely.
    if (g_state_mutex == nullptr)
        return false;

    // Lock the mutex before touching the shared object.
    // portMAX_DELAY means "wait as long as needed" to acquire the lock.
    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    // Copy the shared measured state into the caller's local variable.
    out = g_measured_state;

    // Release the mutex so other tasks may access shared state.
    xSemaphoreGive(g_state_mutex);
    return true;
}

// Write a new measured-state snapshot into shared memory.
bool writeMeasuredState(const MeasuredState &in)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    // Replace the shared measured state with the new input snapshot.
    g_measured_state = in;

    xSemaphoreGive(g_state_mutex);
    return true;
}

//  ==========  HAPTIC COMMAND READ / WRITE =========
//
// The haptic command is typically written by the control/model layer and
// can be read by telemetry/debug code to inspect what torque/current command
// the system most recently requested.

// Read the latest haptic command into the caller-provided output variable.
bool readHapticCommand(HapticCommand &out)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    out = g_haptic_command;

    xSemaphoreGive(g_state_mutex);
    return true;
}

// Write a new haptic command into shared memory.
bool writeHapticCommand(const HapticCommand &in)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    g_haptic_command = in;

    xSemaphoreGive(g_state_mutex);
    return true;
}

//===============  RUNTIME CONFIG READ / WRITE ===========
//
// Runtime configuration contains the user-selected operating mode and any
// tunable parameters associated with that mode.
//
// For example, this might include which haptic model is active and the
// constants/gains used by that model.
//
// This config may be updated by setup/telemetry code and read by the
// control task each loop (or each model update).

// Read the current runtime configuration.
bool readRuntimeConfig(RuntimeConfig &out)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    out = g_runtime_config;

    xSemaphoreGive(g_state_mutex);
    return true;
}

// Write a new runtime configuration into shared memory.
bool writeRuntimeConfig(const RuntimeConfig &in)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    g_runtime_config = in;

    xSemaphoreGive(g_state_mutex);
    return true;
}

// ============== SYSTEM STATE READ / WRITE ===============
// SystemState is the higher-level supervisory/status struct.
//
// Multiple tasks may inspect or update this information, so it is
// protected the same way as the other shared objects.

// Read the current system state into the caller-provided output variable.
bool readSystemState(SystemState &out)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    out = g_system_state;

    xSemaphoreGive(g_state_mutex);
    return true;
}

// Write a new system state into shared memory.
bool writeSystemState(const SystemState &in)
{
    if (g_state_mutex == nullptr)
        return false;

    if (xSemaphoreTake(g_state_mutex, portMAX_DELAY) != pdTRUE)
        return false;

    g_system_state = in;

    xSemaphoreGive(g_state_mutex);
    return true;
}

bool kickControlHeartbeat(SystemState systemState, uint32_t nowUs)
{
    SystemState systemState{};
    if (readSystemState(systemState))
    {
        systemState.control_last_heartbeat_us = nowUs;
        writeSystemState(systemState);
        return true;
    }
    return false;
}