
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-fh4r2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
	askuric/Simple FOC@2.3.4 
	simplefoc/SimpleFOCDrivers@1.0.9 
build_flags = 
	-DSIMPLEFOC_ESP32_USELEDC	
    -DCONFIG_FREERTOS_HZ=1000
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1
    ;-DCONFIG_MCPWM_ENABLE_SLEEP_RETENTION=0
build_src_filter =
    +<*>
    -<test/>
    +<drivers/esp32_driver_mcpwm.cpp>