[env:esp32-s3-fh4r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    askuric/Simple FOC@^2.3.4
    simplefoc/SimpleFOCDrivers@^1.0.9

build_flags =
    -DCONFIG_FREERTOS_HZ=1000
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1

board_build.arduino.memory_type = qio_opi

build_src_filter =
    +<*>
    -<test/> ;resistor.cpp
    ; +<drivers/ModifiedMagneticSensorMT6701SSI.cpp>
    ; +<main.cpp>
    ; +<drivers/spibus.cpp>